AllCops:
  NewCops: enable
  Exclude:
    - Gemfile
    - Gemfile.lock

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - '**/spec/*_spec.rb'
